### ISSUE TITLE
Examples don't work on guest ubuntu - `Couldn't find any pixel format that matches the criterias.`

### ISSUE THREAD

**Issue by yernende** [PistonDevelopers/conrod#757]
When I try to run examples, rust fails with such error:

```
   Compiling conrod v0.37.2 (file:///home/yernende/Development/rust/conrod)
     Running `target/release/examples/all_widgets`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Couldn\'t find any pixel format that matches the criterias."', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x7f7ab230022f - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:     0x7f7ab23031cb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:     0x7f7ab2302e53 - std::panicking::default_hook::hf3839060ccbb8764
   4:     0x7f7ab22f776d - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:     0x7f7ab2303411 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:     0x7f7ab22f86fa - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:     0x7f7ab23033ae - rust_begin_unwind
   8:     0x7f7ab2338aaf - core::panicking::panic_fmt::h93df64e7370b5253
   9:     0x7f7ab216d1ce - core::result::unwrap_failed::hfa264942aa0c849a
  10:     0x7f7ab216a925 - all_widgets::main::hca8753e5503ba0c4
  11:     0x7f7ab2302a98 - std::panicking::try::call::hbbf4746cba890ca7
  12:     0x7f7ab230ccab - __rust_try
  13:     0x7f7ab230cc4e - __rust_maybe_catch_panic
  14:     0x7f7ab230253e - std::rt::lang_start::hbcefdc316c2fbd45
  15:     0x7f7ab1538f44 - __libc_start_main
  16:     0x7f7ab2161318 - <unknown>
  17:                0x0 - <unknown>
error: Process didn't exit successfully: `target/release/examples/all_widgets` (exit code: 101)
```

The same for any other example. I tryed to switch OpenGL version to V2_1 in example's source code, but it didn't change anything.

My OS is Ubuntu 14.04 LTS running upon VirtualBox 5.0.26 (the latest version).

**Comment by mitchmindtree** [comment]
Related to #484

**Comment by mitchmindtree** [comment]
Sorry, related to [this comment in particular](https://github.com/PistonDevelopers/conrod/issues/484#issuecomment-236219153).

**Comment by mitchmindtree** [comment]
Aha, I think I know what's going on.

Recently I fixed a bug in `PistonDevelopers/gfx_texture` where the `UpdateTexture::update` method wouldn't allow for updating sub-sections of textures. While fixing the bug, I noticed that the format argument was being ignored, and that the `Encoder::update_texture` method was being called with the `sRgba8` format type parameter regardless of the format argument given. I fixed it so that it instead called the method with the given format type. However, it seems like the original behaviour (of ignoring the format and using `sRgba8`) was a hack to fix this very same problem that you are now experiencing.

I think the proper way of fixing this would be to add an `sRgba8` variant to the [`Format` enum specified in the PistonDevelopers/texture crate](https://github.com/PistonDevelopers/texture/blob/f5c23bda2f40898e146302b25278f7f481a2699e/src/lib.rs#L149), and then updating the `gfx_texture` methods to handle this correctly. @bvssvni does this sound like a correct fix?

@stianeklund I believe this is the same as your issue.

**Comment by stianeklund** [comment]
@mitchmindtree To add to my previous comment regarding the Glutin example working, is does give me a warning: OpenGL Warning: glXChooseVisual: ignoring attribute 0x22; could this be why it works, and why it does not with Conrod?

**Comment by stianeklund** [comment]
A workaround is to turn off 3D accelerated rendering in Virtualbox; at least in my case.

**Comment by yernende** [comment]
Doesn't work for me(
I tried both disabling and enabling 3D acceleration, but the error remains the same.

**Comment by Kn0rk** [comment]
Same issue here on Debian with fglrx(stable).

Workaround:
Replace
```
let mut window: PistonWindow =
        WindowSettings::new("Canvas Demo", [WIDTH, HEIGHT])
.opengl(opengl).exit_on_esc(true).vsync(true).build().unwrap();
```
with
```
let mut window: PistonWindow<Sdl2Window> =
    WindowSettings::new("Canvas Demo", [WIDTH, HEIGHT])
        .exit_on_esc(true)
        .samples(4)
        .opengl(opengl)
        .build()
        .unwrap();
```

and add/replace the dependencies:
```
extern crate sdl2_window;
use sdl2_window::Sdl2Window;
// in Cargo.toml 
pistoncore-sdl2_window = "0.35.0"
```

Glutin Window creation works on my machine. Piston WindowSettings does not. So i would guess the error originates there and has nothing to do with conrod. Just a guess though...

**Comment by mitchmindtree** [comment]
Going to close this as this seems to be an issue with [PistonDevelopers/piston_window](https://github.com/pistondevelopers/piston_window) rather than with conrod.
